# Generated by Django 5.0.6 on 2024-06-28 16:23

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_cut_off_time', models.TimeField(default=datetime.time(12, 0))),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(unique=True)),
                ('ifc_code', models.CharField(max_length=20)),
                ('account_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_invoice_id', models.IntegerField()),
                ('no_of_partitions', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('post_date', models.DateField()),
                ('post_time', models.TimeField()),
                ('interest', models.FloatField()),
                ('xirr', models.FloatField()),
                ('tenure_in_days', models.IntegerField()),
                ('principle_amt', models.IntegerField()),
                ('expiration_time', models.DateTimeField(default=datetime.time(12, 0))),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('company', 'Company'), ('individual', 'Individual')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FractionalUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('sold', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.invoices')),
            ],
        ),
        migrations.CreateModel(
            name='OutstandingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('updated_at', models.DateField()),
                ('bank_acc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.bankaccountdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_partitions', models.IntegerField()),
                ('total_amount_invested', models.FloatField()),
                ('purchase_date', models.DateField()),
                ('purchase_time', models.TimeField()),
                ('remaining_partitions', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.invoices')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.outstandingbalance')),
            ],
        ),
        migrations.CreateModel(
            name='OutstandingBalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('creditedAmount', models.FloatField(null=True)),
                ('debitedAmount', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('response', 'Response')], max_length=50)),
                ('source', models.CharField(choices=[('bank_to_wallet', 'Bank to Wallet'), ('wallet_to_bank', 'Wallet to Bank'), ('wallet_to_buy', 'Wallet to Buy'), ('sell_to_wallet', 'Sell to Wallet')], max_length=50)),
                ('purpose', models.CharField(max_length=255, null=True)),
                ('time_date', models.DateTimeField()),
                ('bank_acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.bankaccountdetails')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.invoices')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.outstandingbalance')),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('no_of_partitions', models.IntegerField()),
                ('sell_date', models.DateField()),
                ('sell_time', models.TimeField()),
                ('remaining_partitions', models.IntegerField()),
                ('someone_purchased', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.buyers')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.outstandingbalance')),
            ],
        ),
        migrations.CreateModel(
            name='SalePurchaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.buyers')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.fractionalunits')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.sellers')),
            ],
        ),
        migrations.CreateModel(
            name='PanCardNos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_card_no', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.userrole')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pin_code', models.BigIntegerField()),
                ('phone_no', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.userrole')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pin_no', models.BigIntegerField()),
                ('phone_no', models.BigIntegerField()),
                ('company_pan_no', models.CharField(max_length=20)),
                ('public_url_company', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.userrole')),
            ],
        ),
        migrations.AddField(
            model_name='bankaccountdetails',
            name='user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.userrole'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fractionalunits',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
