# Generated by Django 5.0.6 on 2024-06-28 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserFeatures', '0002_remove_buyers_remaining_partitions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractionalunits',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.userrole'),
        ),
    ]
