# Generated by Django 5.0.6 on 2024-06-28 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserFeatures', '0003_alter_fractionalunits_current_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractionalunits',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
