# Generated by Django 5.0.6 on 2024-06-29 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserFeatures', '0004_alter_fractionalunits_current_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.userrole'),
        ),
        migrations.AlterField(
            model_name='fractionalunits',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserFeatures.userrole'),
        ),
    ]
